CC=g++
CFLAGS=-c -Wall -Werror -pedantic

all: clean builder

builder: builder.o
	$(CC) builder.o -o builder

builder.o: builder.c
	$(CC) $(CFLAGS) builder.c

clean:
	rm -f *.o *~ *.out core builder 

